### ISSUE TITLE
Add check of encryption status

### ISSUE THREAD

**Issue by kpichardie** [shaftmx/passkeeper#30]
Example : 
import gnupg

gpg = gnupg.GPG()
with open('/opt/mypasskeeper/default.ini', 'r') as f:
        status = gpg.encrypt_file(
            f,
            recipients=None,
            symmetric='AES256',
            armor=True,
            passphrase='passphrase',
            output='/opt/mypasskeeper/encrypted/default.ini.passkeeper')

print 'ok: ', status.ok
print 'status: ', status.status
print 'stderr: ', status.stderr

quit()

**Comment by kpichardie** [comment]
Typical issue :
>>> print 'ok: ', status.ok
ok:  False
>>> print 'status: ', status.status
status:  
>>> print 'stderr: ', status.stderr
stderr:  gpg: fatal: can't create directory `/var/www/.gnupg': Permission denied
secmem usage: 0/0 bytes in 0/0 blocks of pool 0/65536

**Comment by gaelL** [comment]
Can you add more informations on this issue, what is your problem, what are you expecting ?

**Comment by kpichardie** [comment]
The issue is in https://github.com/shaftmx/passkeeper/blob/master/passkeeper/crypt.py#L26-L36

GPG encryption status is not managed. 

If it fails, encryption process continue while a file isn't succesfully encrypted

**Comment by gaelL** [comment]
Ok so, it's definitely not here to check the status. https://github.com/shaftmx/passkeeper/blob/master/passkeeper/crypt.py#L26-L36 

It's just a wrapper function that encrypt a file and return the entrypt status.

It's the same as `gpg.encrypt_file` this function should not exit, print or stop a program if encrypt fail. Your program should decide what to do if encrypt fail or not. Not the function itself. So in this case the error is handled : https://github.com/shaftmx/passkeeper/blob/master/passkeeper/crypt.py#L36
The error is returned to the parent method and logged here : https://github.com/shaftmx/passkeeper/blob/master/passkeeper/__init__.py#L93

So for now, we just have logs when a file is not encrypted. It's not a bug for me, the error is handled and go in a log file. You want to change the behavior. 

I can understand that you want to stop processing is one file failed but for that we need to think a little bit more. If we simply stop the actual `encrypt` function because one file failed, it will let your git in a bad state.

**Comment by kpichardie** [comment]
Thanks for your analyse, but in fact the log isn't correct :
https://github.com/shaftmx/passkeeper/blob/master/passkeeper/__init__.py#L93
This return a hash and doesn't log fail.

So I advice to log the issue or catch it to be able to check the issue.

**Comment by gaelL** [comment]
I didn't understand what you mean by `This return a hash and doesn't log fail` The gpg command return an object and I log the `myobject.status` attribute. But this attribute in your case is really not explicite
```
need symmetric passphrase
```
So I changed it to stderr for the first shot

https://github.com/shaftmx/passkeeper/commit/0481c28089c2cc9442c46e625e1ccdc819bd7646

I go to bed, let's discuss this tomorrow

Thank

**Comment by kpichardie** [comment]
Thanks perfect
